spring:
  application:
    name: greeting
  cloud:
    config:
      enabled: false
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
greeting-service:
  greeting: "default ola"
  default-value: "mundo"